name: quiz_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # Untuk mempercantik teks dengan Google Fonts
  lottie: ^3.1.0 # Untuk animasi splash screen atau tampilan hasil kuis

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # Pindahkan ke dev_dependencies ✅

flutter:
  uses-material-design: true

  assets:
    - assets/logoo.png # Pastikan file ini ada di folder assets ✅

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoo.png"
